/**
 * `SpellEffects` (TrinityCore 3.3.5): what effect slot N of a spell does.
 * Generated from TrinityCore 3.3.5's `SharedDefines.h`/`SpellAuraDefines.h` —
 * every enum member, `null` for the handful TrinityCore itself never named
 * (reserved/unused ids kept only for numeric stability).
 */
export const spellEffectNames: Record<number, string | null> = {
  0: 'None',
  1: 'Instakill',
  2: 'School Damage',
  3: 'Dummy',
  4: 'Portal Teleport',
  5: 'Teleport Units',
  6: 'Apply Aura',
  7: 'Environmental Damage',
  8: 'Power Drain',
  9: 'Health Leech',
  10: 'Heal',
  11: 'Bind',
  12: 'Portal',
  13: 'Ritual Base',
  14: 'Ritual Specialize',
  15: 'Ritual Activate Portal',
  16: 'Quest Complete',
  17: 'Weapon Damage Noschool',
  18: 'Resurrect',
  19: 'Add Extra Attacks',
  20: 'Dodge',
  21: 'Evade',
  22: 'Parry',
  23: 'Block',
  24: 'Create Item',
  25: 'Weapon',
  26: 'Defense',
  27: 'Persistent Area Aura',
  28: 'Summon',
  29: 'Leap',
  30: 'Energize',
  31: 'Weapon Percent Damage',
  32: 'Trigger Missile',
  33: 'Open Lock',
  34: 'Summon Change Item',
  35: 'Apply Area Aura Party',
  36: 'Learn Spell',
  37: 'Spell Defense',
  38: 'Dispel',
  39: 'Language',
  40: 'Dual Wield',
  41: 'Jump',
  42: 'Jump Dest',
  43: 'Teleport Units Face Caster',
  44: 'Skill Step',
  45: 'Add Honor',
  46: 'Spawn',
  47: 'Trade Skill',
  48: 'Stealth',
  49: 'Detect',
  50: 'Trans Door',
  51: 'Force Critical Hit',
  52: 'Guarantee Hit',
  53: 'Enchant Item',
  54: 'Enchant Item Temporary',
  55: 'Tamecreature',
  56: 'Summon Pet',
  57: 'Learn Pet Spell',
  58: 'Weapon Damage',
  59: 'Create Random Item',
  60: 'Proficiency',
  61: 'Send Event',
  62: 'Power Burn',
  63: 'Threat',
  64: 'Trigger Spell',
  65: 'Apply Area Aura Raid',
  66: 'Create Mana Gem',
  67: 'Heal Max Health',
  68: 'Interrupt Cast',
  69: 'Distract',
  70: 'Pull',
  71: 'Pickpocket',
  72: 'Add Farsight',
  73: 'Untrain Talents',
  74: 'Apply Glyph',
  75: 'Heal Mechanical',
  76: 'Summon Object Wild',
  77: 'Script Effect',
  78: 'Attack',
  79: 'Sanctuary',
  80: 'Add Combo Points',
  81: 'Create House',
  82: 'Bind Sight',
  83: 'Duel',
  84: 'Stuck',
  85: 'Summon Player',
  86: 'Activate Object',
  87: 'Gameobject Damage',
  88: 'Gameobject Repair',
  89: 'Gameobject Set Destruction State',
  90: 'Kill Credit',
  91: 'Threat All',
  92: 'Enchant Held Item',
  93: 'Force Deselect',
  94: 'Self Resurrect',
  95: 'Skinning',
  96: 'Charge',
  97: 'Cast Button',
  98: 'Knock Back',
  99: 'Disenchant',
  100: 'Inebriate',
  101: 'Feed Pet',
  102: 'Dismiss Pet',
  103: 'Reputation',
  104: 'Summon Object Slot1',
  105: 'Summon Object Slot2',
  106: 'Summon Object Slot3',
  107: 'Summon Object Slot4',
  108: 'Dispel Mechanic',
  109: 'Resurrect Pet',
  110: 'Destroy All Totems',
  111: 'Durability Damage',
  112: null,
  113: 'Resurrect New',
  114: 'Attack Me',
  115: 'Durability Damage Pct',
  116: 'Skin Player Corpse',
  117: 'Spirit Heal',
  118: 'Skill',
  119: 'Apply Area Aura Pet',
  120: 'Teleport Graveyard',
  121: 'Normalized Weapon Dmg',
  122: null,
  123: 'Send Taxi',
  124: 'Pull Towards',
  125: 'Modify Threat Percent',
  126: 'Steal Beneficial Buff',
  127: 'Prospecting',
  128: 'Apply Area Aura Friend',
  129: 'Apply Area Aura Enemy',
  130: 'Redirect Threat',
  131: 'Play Sound',
  132: 'Play Music',
  133: 'Unlearn Specialization',
  134: 'Kill Credit2',
  135: 'Call Pet',
  136: 'Heal Pct',
  137: 'Energize Pct',
  138: 'Leap Back',
  139: 'Clear Quest',
  140: 'Force Cast',
  141: 'Force Cast With Value',
  142: 'Trigger Spell With Value',
  143: 'Apply Area Aura Owner',
  144: 'Knock Back Dest',
  145: 'Pull Towards Dest',
  146: 'Activate Rune',
  147: 'Quest Fail',
  148: 'Trigger Missile Spell With Value',
  149: 'Charge Dest',
  150: 'Quest Start',
  151: 'Trigger Spell 2',
  152: 'Summon Raf Friend',
  153: 'Create Tamed Pet',
  154: 'Discover Taxi',
  155: 'Titan Grip',
  156: 'Enchant Item Prismatic',
  157: 'Create Item 2',
  158: 'Milling',
  159: 'Allow Rename Pet',
  160: 'Force Cast 2',
  161: 'Talent Spec Count',
  162: 'Talent Spec Select',
  163: null,
  164: 'Remove Aura',
}
