/**
 * `AuraType` (TrinityCore 3.3.5): what an aura-applying effect slot attaches.
 * Generated from TrinityCore 3.3.5's `SharedDefines.h`/`SpellAuraDefines.h` —
 * every enum member, `null` for the handful TrinityCore itself never named
 * (reserved/unused ids kept only for numeric stability).
 */
export const spellAuraNames: Record<number, string | null> = {
  0: 'None',
  1: 'Bind Sight',
  2: 'Mod Possess',
  3: 'Periodic Damage',
  4: 'Dummy',
  5: 'Mod Confuse',
  6: 'Mod Charm',
  7: 'Mod Fear',
  8: 'Periodic Heal',
  9: 'Mod Attackspeed',
  10: 'Mod Threat',
  11: 'Mod Taunt',
  12: 'Mod Stun',
  13: 'Mod Damage Done',
  14: 'Mod Damage Taken',
  15: 'Damage Shield',
  16: 'Mod Stealth',
  17: 'Mod Stealth Detect',
  18: 'Mod Invisibility',
  19: 'Mod Invisibility Detect',
  20: 'Obs Mod Health',
  21: 'Obs Mod Power',
  22: 'Mod Resistance',
  23: 'Periodic Trigger Spell',
  24: 'Periodic Energize',
  25: 'Mod Pacify',
  26: 'Mod Root',
  27: 'Mod Silence',
  28: 'Reflect Spells',
  29: 'Mod Stat',
  30: 'Mod Skill',
  31: 'Mod Increase Speed',
  32: 'Mod Increase Mounted Speed',
  33: 'Mod Decrease Speed',
  34: 'Mod Increase Health',
  35: 'Mod Increase Energy',
  36: 'Mod Shapeshift',
  37: 'Effect Immunity',
  38: 'State Immunity',
  39: 'School Immunity',
  40: 'Damage Immunity',
  41: 'Dispel Immunity',
  42: 'Proc Trigger Spell',
  43: 'Proc Trigger Damage',
  44: 'Track Creatures',
  45: 'Track Resources',
  46: null,
  47: 'Mod Parry Percent',
  48: 'Periodic Trigger Spell From Client',
  49: 'Mod Dodge Percent',
  50: 'Mod Critical Healing Amount',
  51: 'Mod Block Percent',
  52: 'Mod Weapon Crit Percent',
  53: 'Periodic Leech',
  54: 'Mod Hit Chance',
  55: 'Mod Spell Hit Chance',
  56: 'Transform',
  57: 'Mod Spell Crit Chance',
  58: 'Mod Increase Swim Speed',
  59: 'Mod Damage Done Creature',
  60: 'Mod Pacify Silence',
  61: 'Mod Scale',
  62: 'Periodic Health Funnel',
  63: null,
  64: 'Periodic Mana Leech',
  65: 'Mod Casting Speed Not Stack',
  66: 'Feign Death',
  67: 'Mod Disarm',
  68: 'Mod Stalked',
  69: 'School Absorb',
  70: 'Extra Attacks',
  71: 'Mod Spell Crit Chance School',
  72: 'Mod Power Cost School Pct',
  73: 'Mod Power Cost School',
  74: 'Reflect Spells School',
  75: 'Mod Language',
  76: 'Far Sight',
  77: 'Mechanic Immunity',
  78: 'Mounted',
  79: 'Mod Damage Percent Done',
  80: 'Mod Percent Stat',
  81: 'Split Damage Pct',
  82: 'Water Breathing',
  83: 'Mod Base Resistance',
  84: 'Mod Regen',
  85: 'Mod Power Regen',
  86: 'Channel Death Item',
  87: 'Mod Damage Percent Taken',
  88: 'Mod Health Regen Percent',
  89: 'Periodic Damage Percent',
  90: null,
  91: 'Mod Detect Range',
  92: 'Prevents Fleeing',
  93: 'Mod Unattackable',
  94: 'Interrupt Regen',
  95: 'Ghost',
  96: 'Spell Magnet',
  97: 'Mana Shield',
  98: 'Mod Skill Talent',
  99: 'Mod Attack Power',
  100: 'Auras Visible',
  101: 'Mod Resistance Pct',
  102: 'Mod Melee Attack Power Versus',
  103: 'Mod Total Threat',
  104: 'Water Walk',
  105: 'Feather Fall',
  106: 'Hover',
  107: 'Add Flat Modifier',
  108: 'Add Pct Modifier',
  109: 'Add Target Trigger',
  110: 'Mod Power Regen Percent',
  111: 'Add Caster Hit Trigger',
  112: 'Override Class Scripts',
  113: 'Mod Ranged Damage Taken',
  114: 'Mod Ranged Damage Taken Pct',
  115: 'Mod Healing',
  116: 'Mod Regen During Combat',
  117: 'Mod Mechanic Resistance',
  118: 'Mod Healing Pct',
  119: null,
  120: 'Untrackable',
  121: 'Empathy',
  122: 'Mod Offhand Damage Pct',
  123: 'Mod Target Resistance',
  124: 'Mod Ranged Attack Power',
  125: 'Mod Melee Damage Taken',
  126: 'Mod Melee Damage Taken Pct',
  127: 'Ranged Attack Power Attacker Bonus',
  128: 'Mod Possess Pet',
  129: 'Mod Speed Always',
  130: 'Mod Mounted Speed Always',
  131: 'Mod Ranged Attack Power Versus',
  132: 'Mod Increase Energy Percent',
  133: 'Mod Increase Health Percent',
  134: 'Mod Mana Regen Interrupt',
  135: 'Mod Healing Done',
  136: 'Mod Healing Done Percent',
  137: 'Mod Total Stat Percentage',
  138: 'Mod Melee Haste',
  139: 'Force Reaction',
  140: 'Mod Ranged Haste',
  141: 'Mod Ranged Ammo Haste',
  142: 'Mod Base Resistance Pct',
  143: 'Mod Resistance Exclusive',
  144: 'Safe Fall',
  145: 'Mod Pet Talent Points',
  146: 'Allow Tame Pet Type',
  147: 'Mechanic Immunity Mask',
  148: 'Retain Combo Points',
  149: 'Reduce Pushback',
  150: 'Mod Shield Blockvalue Pct',
  151: 'Track Stealthed',
  152: 'Mod Detected Range',
  153: 'Split Damage Flat',
  154: 'Mod Stealth Level',
  155: 'Mod Water Breathing',
  156: 'Mod Reputation Gain',
  157: 'Pet Damage Multi',
  158: 'Mod Shield Blockvalue',
  159: 'No PVP Credit',
  160: 'Mod AOE Avoidance',
  161: 'Mod Health Regen In Combat',
  162: 'Power Burn',
  163: 'Mod Crit Damage Bonus',
  164: null,
  165: 'Melee Attack Power Attacker Bonus',
  166: 'Mod Attack Power Pct',
  167: 'Mod Ranged Attack Power Pct',
  168: 'Mod Damage Done Versus',
  169: 'Mod Crit Percent Versus',
  170: 'Detect Amore',
  171: 'Mod Speed Not Stack',
  172: 'Mod Mounted Speed Not Stack',
  173: null,
  174: 'Mod Spell Damage Of Stat Percent',
  175: 'Mod Spell Healing Of Stat Percent',
  176: 'Spirit Of Redemption',
  177: 'AOE Charm',
  178: 'Mod Debuff Resistance',
  179: 'Mod Attacker Spell Crit Chance',
  180: 'Mod Flat Spell Damage Versus',
  181: null,
  182: 'Mod Resistance Of Stat Percent',
  183: 'Mod Critical Threat',
  184: 'Mod Attacker Melee Hit Chance',
  185: 'Mod Attacker Ranged Hit Chance',
  186: 'Mod Attacker Spell Hit Chance',
  187: 'Mod Attacker Melee Crit Chance',
  188: 'Mod Attacker Ranged Crit Chance',
  189: 'Mod Rating',
  190: 'Mod Faction Reputation Gain',
  191: 'Use Normal Movement Speed',
  192: 'Mod Melee Ranged Haste',
  193: 'Melee Slow',
  194: 'Mod Target Absorb School',
  195: 'Mod Target Ability Absorb School',
  196: 'Mod Cooldown',
  197: 'Mod Attacker Spell And Weapon Crit Chance',
  198: null,
  199: 'Mod Increases Spell Pct To Hit',
  200: 'Mod Xp Pct',
  201: 'Fly',
  202: 'Ignore Combat Result',
  203: 'Mod Attacker Melee Crit Damage',
  204: 'Mod Attacker Ranged Crit Damage',
  205: 'Mod School Crit Dmg Taken',
  206: 'Mod Increase Vehicle Flight Speed',
  207: 'Mod Increase Mounted Flight Speed',
  208: 'Mod Increase Flight Speed',
  209: 'Mod Mounted Flight Speed Always',
  210: 'Mod Vehicle Speed Always',
  211: 'Mod Flight Speed Not Stack',
  212: 'Mod Ranged Attack Power Of Stat Percent',
  213: 'Mod Rage From Damage Dealt',
  214: null,
  215: 'Arena Preparation',
  216: 'Haste Spells',
  217: 'Mod Melee Haste 2',
  218: 'Haste Ranged',
  219: 'Mod Mana Regen From Stat',
  220: 'Mod Rating From Stat',
  221: 'Mod Detaunt',
  222: null,
  223: 'Raid Proc From Charge',
  224: null,
  225: 'Raid Proc From Charge With Value',
  226: 'Periodic Dummy',
  227: 'Periodic Trigger Spell With Value',
  228: 'Detect Stealth',
  229: 'Mod AOE Damage Avoidance',
  230: null,
  231: 'Proc Trigger Spell With Value',
  232: 'Mechanic Duration Mod',
  233: 'Change Model For All Humanoids',
  234: 'Mechanic Duration Mod Not Stack',
  235: 'Mod Dispel Resist',
  236: 'Control Vehicle',
  237: 'Mod Spell Damage Of Attack Power',
  238: 'Mod Spell Healing Of Attack Power',
  239: 'Mod Scale 2',
  240: 'Mod Expertise',
  241: 'Force Move Forward',
  242: 'Mod Spell Damage From Healing',
  243: 'Mod Faction',
  244: 'Comprehend Language',
  245: 'Mod Aura Duration By Dispel',
  246: 'Mod Aura Duration By Dispel Not Stack',
  247: 'Clone Caster',
  248: 'Mod Combat Result Chance',
  249: 'Convert Rune',
  250: 'Mod Increase Health 2',
  251: 'Mod Enemy Dodge',
  252: 'Mod Speed Slow All',
  253: 'Mod Block Crit Chance',
  254: 'Mod Disarm Offhand',
  255: 'Mod Mechanic Damage Taken Percent',
  256: 'No Reagent Use',
  257: 'Mod Target Resist By Spell Class',
  258: null,
  259: 'Mod HOT Pct',
  260: 'Screen Effect',
  261: 'Phase',
  262: 'Ability Ignore Aurastate',
  263: 'Allow Only Ability',
  264: null,
  265: null,
  266: null,
  267: 'Mod Immune Aura Apply School',
  268: 'Mod Attack Power Of Stat Percent',
  269: 'Mod Ignore Target Resist',
  270: 'Mod Ability Ignore Target Resist',
  271: 'Mod Spell Damage From Caster',
  272: 'Ignore Melee Reset',
  273: 'X Ray',
  274: 'Ability Consume No Ammo',
  275: 'Mod Ignore Shapeshift',
  276: 'Mod Damage Done For Mechanic',
  277: 'Mod Max Affected Targets',
  278: 'Mod Disarm Ranged',
  279: 'Initialize Images',
  280: 'Mod Armor Penetration Pct',
  281: 'Mod Honor Gain Pct',
  282: 'Mod Base Health Pct',
  283: 'Mod Healing Received',
  284: 'Linked',
  285: 'Mod Attack Power Of Armor',
  286: 'Ability Periodic Crit',
  287: 'Deflect Spells',
  288: 'Ignore Hit Direction',
  289: 'Prevent Durability Loss',
  290: 'Mod Crit Pct',
  291: 'Mod Xp Quest Pct',
  292: 'Open Stable',
  293: 'Override Spells',
  294: 'Prevent Regenerate Power',
  295: null,
  296: 'Set Vehicle ID',
  297: 'Block Spell Family',
  298: 'Strangulate',
  299: null,
  300: 'Share Damage Pct',
  301: 'School Heal Absorb',
  302: null,
  303: 'Mod Damage Done Versus Aurastate',
  304: 'Mod Fake Inebriate',
  305: 'Mod Minimum Speed',
  306: null,
  307: 'Heal Absorb Test',
  308: 'Mod Crit Chance For Caster',
  309: null,
  310: 'Mod Creature AOE Damage Avoidance',
  311: null,
  312: null,
  313: null,
  314: 'Prevent Resurrection',
  315: 'Underwater Walking',
  316: 'Periodic Haste',
}
