use tauri::State;
use crate::db::DbState;

/// Execute a list of SQL statements inside a single transaction.
///
/// Editors save an entity and all of its sub-tables through this command so a
/// failure in any statement rolls back the whole save instead of leaving the
/// database half-updated. Statements are generated by the frontend diff
/// engine (the same one that produces the exported session script).
#[tauri::command]
pub async fn execute_batch(
    state: State<'_, DbState>,
    queries: Vec<String>,
) -> Result<(), String> {
    if queries.is_empty() {
        return Ok(());
    }

    let db = state.pool.read().await;
    let pool = db.as_ref().ok_or("Not connected to database")?;

    let mut tx = pool
        .begin()
        .await
        .map_err(|e| format!("Failed to start transaction: {}", e))?;

    for query in &queries {
        if let Err(e) = sqlx::query(query).execute(&mut *tx).await {
            let rollback = tx.rollback().await;
            let mut message = format!("Query failed, transaction rolled back: {} — {}", e, query);
            if let Err(re) = rollback {
                message.push_str(&format!(" (rollback also failed: {})", re));
            }
            log::error!("{}", message);
            return Err(message);
        }
    }

    tx.commit()
        .await
        .map_err(|e| format!("Failed to commit transaction: {}", e))?;

    log::info!("Executed batch of {} statements", queries.len());
    Ok(())
}
